<?php

/* PFP - Prefab Paragraphs */

/*
** Provide valid Paragraph Type blueprints.
**
** @todo Allow other modules to alter and add to this list? Search for all
**       blueprints folders?
*/
function pfp_get_blueprints($paragraph_type = NULL) {
    $path = backdrop_get_path('module', 'pfp') . '/blueprints';
    $blueprints = array(
        'pfp_embed' => array(
            'machine_name' => 'pfp_embed',
            'name' => t('Embed'),
            'description' => t('A simple text area with no WYSIWYG for pasting embed code in.'),
            'path' => $path,
            'configs' => array(
                'field.field.pfp_text_area',
                'field.bundle.paragraphs_item.pfp_embed',
                'field.instance.paragraphs_item.pfp_embed.pfp_text_area',
                'field.bundle.paragraphs_item.pfp_embed',
            ),
            'dependencies' => array(
                '',
            ),
        ),
        'pfp_text' => array(
            'machine_name' => 'pfp_text',
            'name' => t('Text'),
            'description' => t('A text area with section title and settings for column display.'),
            'path' => $path,
            'configs' => array(
                'classy_paragraphs_ui.sets',
                'field.field.pfp_section_title',
                'field.field.pfp_text_area',
                'field.field.pfp_columns',
                'field.instance.paragraphs_item.pfp_text.pfp_section_title',
                'field.instance.paragraphs_item.pfp_text.pfp_text_area',
                'field.instance.paragraphs_item.pfp_text.pfp_columns',
                'field_group.field_group.paragraphs_item.pfp_text.form.group_settings',
                'field.bundle.paragraphs_item.pfp_text',
            ),
            'dependencies' => array(
                'classy_paragraphs',
                'field_group',
            ),
        ),
        'pfp_image' => array(
            'machine_name' => 'pfp_image',
            'name' => t('Image'),
            'description' => t('An image field that allows free cropping, with settings for section width and background color.'),
            'path' => $path,
            'configs' => array(
                'classy_paragraphs_ui.sets',
                'image.style.pfp_free_crop',
                'field.field.pfp_image',
                'field.field.pfp_background_color',
                'field.field.pfp_width',
                'field.instance.paragraphs_item.pfp_image.pfp_image',
                'field.instance.paragraphs_item.pfp_image.pfp_background_color',
                'field.instance.paragraphs_item.pfp_image.pfp_width',
                'field_group.field_group.paragraphs_item.pfp_image.form.group_settings',
                'field.bundle.paragraphs_item.pfp_image',
            ),
            'dependencies' => array(
                'classy_paragraphs',
                'field_group',
                'image',
                'manualcrop',
            ),
        ),
    );
    if (!empty($paragraph_type)) {
        if (!empty($blueprints[$paragraph_type])) {
            // Return single blueprint.
            return $blueprints[$paragraph_type];
        }
        else {
            // Invalid Paragraph Type requested.
            return FALSE;
        }
    }
    else {
        // Return all results.
        return $blueprints;
    }
}

/**
 * Implements hook_permission().
 */
function pfp_permission() {
  return array(
    'administer prefab paragraphs' => array(
      'title' => t('Administer Prefab Paragraphs'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function pfp_menu() {
  $items['admin/structure/paragraphs/pfp'] = array(
    'title' => t('Blueprints'),
    'description' => t('List available Paragraph type blueprints'),
    'page callback' => 'pfp_overview_blueprints',
    'access arguments' => array('administer prefab paragraphs'),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/structure/paragraphs/pfp/%/build'] = array(
    'title' => t('Build a Paragraph type from a blueprint'),
    'description' => t('Build a Paragraph type from a blueprint'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('pfp_build_paragraph_type', 4),
    'access arguments' => array('administer prefab paragraphs'),
  );
  return $items;
}

/**
 * List all available Paragraph type blueprints.
 */
function pfp_overview_blueprints() {
    backdrop_set_title(t('Prefab Paragraph blueprints'));
    $blueprints = pfp_get_blueprints();
    $header_unbuilt = array(
        t('Available Blueprints'),
        t('Operations'),
    );
    $header_built = array(
        t('Used Blueprints'),
        t('Operations'),
    );
    $rows_unbuilt = array();
    $rows_built = array();

    foreach ($blueprints as $key => $blueprint) {
        $already_exists = (config_get('paragraphs.type.' . $blueprint['machine_name'], 'bundle')) ? 1 : 0;
        $blueprint_url_str = str_replace('_', '-', $key);
        $blueprint_type = new StdClass();
        $blueprint_type->type = $key;
        $blueprint_type->description = $blueprint['description'];
        $row = array(theme('node_admin_overview', array('name' => $blueprint['name'], 'type' => $blueprint_type)));
        $links = array();
        if (!$already_exists) {
            // Doesn't exist -- allow it to be built.
            $links['build'] = array(
                'title' => t('Use this blueprint'),
                'href' => 'admin/structure/paragraphs/pfp/' . $blueprint_url_str . '/build',
                'weight' => 0,
            );
            $row[] = array(
                'data' => array(
                    '#type' => 'operations',
                    '#links' => $links,
                ),
            );
            $rows_unbuilt[$blueprint['name']] = $row;
        }
        else {
            // Already exists -- do not try to rebuild.
            $links['configure'] = array(
                'title' => t('Manage fields'),
                'href' => 'admin/structure/paragraphs/' . $blueprint_url_str . '/fields',
                'weight' => 0,
            );
            $row[] = array(
                'data' => array(
                    '#type' => 'operations',
                    '#links' => $links,
                ),
            );
            $rows_built[$blueprint['name']] = $row;
        }
    }
    ksort($rows_unbuilt);
    ksort($rows_built);
    $build['pfp_table_unbuilt'] = array(
    '#theme' => 'table',
    '#header' => $header_unbuilt,
    '#rows' => $rows_unbuilt,
    '#empty' => t('No Paragraph type blueprints available.'),
    );
    $build['pfp_table_built'] = array(
    '#theme' => 'table',
    '#header' => $header_built,
    '#rows' => $rows_built,
    '#empty' => t('No Paragraph type blueprints have been used.'),
    );

    return $build;
}

/*
** Build a paragraph type from the blueprints.
*/
function pfp_build_paragraph_type($form, &$form_state, $paragraph_type = NULL) {
    $paragraph_type = str_replace('-', '_', $paragraph_type);
    $error = array();
    if (!empty($paragraph_type)) {
        // See if this Paragraph Type has a valid blueprint.
        $blueprint = pfp_get_blueprints($paragraph_type);
        if (!empty($blueprint)) {
            $name = $blueprint['name'];
            $pfp_config = config('paragraphs.type.' . $paragraph_type);
            // See if this Paragraph Type already exists on this site.
            if ($pfp_config->isNew()) {
                // If not, check dependencies and create the Paragraph Type.
                $fail = 0;
                foreach ($blueprint['dependencies'] as $dependency) {
                    if (!empty($dependency) && !module_exists($dependency)) {
                        $fail = 1;
                        $error[] = t('The %name Paragraph type could not be built because a dependency is missing.', array('%name' => $name));
                    }
                }
                if (!$fail) {
                    foreach ($blueprint['configs'] as $needed_config) {
                        $result = _pfp_build_config($blueprint['path'], $needed_config);
                        if (!empty($result)) {
                            $error[] = $result;
                        }
                    }
                    $result = _pfp_build_config($blueprint['path'], 'paragraphs.type.' . $blueprint['machine_name']);
                    if (!empty($result)) {
                        $error[] = $result;
                    }
                }
                else {
                    $error[] = t('The %name Paragraph type could not be built.', array('%name' => $name));
                }
            }
            else {
                // This Paragraph Type already exists.
                $error[] = t('The %name Paragraph type already exists.', array('%name' => $name));
            }
        }
        else {
            $error[] = t('The requested blueprint does not exist.');
        }
        if (empty($error)) {
            backdrop_set_message(t('The %name Paragraph type has been built according to the blueprint.', array('%name' => $name)));
        }
    }
    else {
        // @todo allow "all" to build all available Paragraphs? Maybe.
    }

    if (!empty($error)) {
        backdrop_set_message(implode('<br />', $error), 'warning');
    }
    backdrop_goto('admin/structure/paragraphs/pfp');
}

/**
 * Build a particular config file from a blueprint.
 */
function _pfp_build_config($path = '', $machine_name = '') {
    $error = '';
    if (!empty($path) && !empty($machine_name)) {
        $config = config($machine_name);
        if ($config->isNew()) {
            $storage = new ConfigFileStorage($path);
            $data = $storage->read($machine_name);
            $config->setData($data);
            module_invoke_all('config_create', $config);
            $config->save();
            cache_clear_all();
        }
        else {
            $error = t('Note: %config already exists and has not been changed. This could affect default functionality if it has been modified from the original settings.', array('%config' => $machine_name));
        }
    }
    else {
        $error = t('There was an error installing this blueprint.');
    }
    return $error;
}
